Feature/nre/3 secured authentification form
nicolasrll/blog pull request #18
Opened 2020-05-22 10:54 UTC by nicolasrll

#3

2020-05-28 17:26 UTC, fmoy approved these changes

2020-05-28 17:26 UTC, fmoy commented on config/conf.php
> +    define('DSN', 'mysql:host=localhost');
ne pas versionner ce fichier utiliser le .dist

2020-05-28 17:26 UTC, fmoy commented on core/DefaultControllerAbstract.php
> +    public function hasCSRFToken()
setTokenCSRF / generateTokenCSRF

2020-05-28 17:26 UTC, fmoy commented on core/DefaultControllerAbstract.php
> +    public function hasCSRFToken()
typer le retour

2020-05-28 17:26 UTC, fmoy commented on src/Controller/AuthentificationController.php
> +            //$this->csrfTokenCheck($formValues['token']);
virer les commentaires

2020-05-28 17:26 UTC, fmoy commented on src/Controller/AuthentificationController.php
>          if ($this->isSubmited('authentification')) {
j'ajouterais le test sur le token

2020-05-28 17:26 UTC, fmoy commented on src/Controller/AuthentificationController.php
> +                !$this->csrfTokenCheck($formValues['token'])
retirer le check sur le role (la redirection s'en chargera) retirer le check sur le token, le faire plus tot, et ne plus utiliser cette methode, utiliser celle de l'indexAction();

2020-05-28 17:26 UTC, fmoy commented on src/Controller/AuthentificationController.php
> +    public function csrfTokenCheck($formTokenValue): bool
verifyTokenCsrf() / checkTokenCsrf()

2020-05-28 17:26 UTC, fmoy commented on template/authentification-admin.html.twig
> +                            <input type="hidden" name="authentification[token]" value="{{ session.token }}">
à voir pour gérer plusieurs token (un par formulaire pour éviter les conflits)

2020-05-28 17:32 UTC, fmoy requested changes

2020-05-28 17:32 UTC, fmoy commented on .gitignore
> +.idea/
revois mes anciennes remarques

2020-08-12 19:10 UTC, NicolasRllValidator approved these changes

2020-08-12 19:10 UTC, merged